version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    ports:
      - '5400:5400'
    expose:
      - '5400'
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    networks:
      - db-network
    command: -p 5400

  server:
    ports:
      - 8000:8000
    depends_on: 
      - db
    build: ./
    restart: on-failure
    command: ./zero2prod
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@db:5400/${PG_DBNAME}
    networks:
      - db-network
    
networks:
  db-network:
    driver: bridge
